export const phrases = [
    {
        en: "See you later!",
        ru: "Увидимся позже!",
        topic: "greetings",
        altEn: ["see you soon", "see you"],
        altRu: ["до скорого", "до встречи", "до скорой встречи", "до скорых встреч", "еще увидимся", "ещё увидимся", "увидимся позднее"],
    },
    {
        en: "Good luck!",
        ru: "Удачи!",
        topic: "greetings",
        altEn: [],
        altRu: [],
    },
    {
        en: "Long time no see!",
        ru: "Давно не виделись!",
        topic: "greetings",
        altEn: ["long time no see you"],
        altRu: ["давненько не виделись"],
    },
    {
        en: "How is it going?",
        ru: "Как идут дела?",
        topic: "greetings",
        altEn: ["how are things going", "howre things going", "hows it going", ],
        altRu: ["как дела", "как делишки"],
    },
    {
        en: "How's life?",
        ru: "Как жизнь?",
        topic: "greetings",
        altEn: ["how is life", "how is your life"],
        altRu: [],
    },
    {
        en: "How are things?",
        ru: "Как оно?",
        topic: "greetings",
        altEn: ["howre things"],
        altRu: ["как дела"],
    },
    {
        en: "What are you up to?",
        ru: "Чем занимаешься?",
        topic: "greetings",
        altEn: ["what are you doing", "whatre you doing", "what do you do"],
        altRu: ["что ты задумал", "что вы задумали", "чем занимаетесь", "чем вы занимаетесь", "чем ты занимаешься", "чем собираешься заняться", "чем собираетесь заняться", "чем думаешь заняться", "чем думаете заняться"],
    },
    {
        en: "What have you been up to?",
        ru: "Что ты делал все это время?",
        topic: "greetings",
        altEn: ["what did you do all this time", "whatve you been up to"],
        altRu: ["чем ты занимался все это время", "что вы делали все это время", "чем вы занимались всё это время"],
    },
    {
        en: "See you soon!",
        ru: "До скорого!",
        topic: "greetings",
        altEn: ["see you later"],
        altRu: ["до скорой встречи", "до скорых встреч", "скоро увидимся"],
    },
    {
        en: "Till next time!",
        ru: "До следующего раза!",
        topic: "greetings",
        altEn: ["untill next time"],
        altRu: ["до скорого"],
    },
    {
        en: "Take care!",
        ru: "Береги себя!",
        topic: "greetings",
        altEn: ["take care of yourself"],
        altRu: ["берегите себя", "будьте осторожны", "будь осторожен", "берегись", "берегитесь"],
    },
    {
        en: "Let's talk later!",
        ru: "Давайте поговорим позже!",
        topic: "greetings",
        altEn: ["talk to you later", "let us talk later"],
        altRu: ["поговорим позже"],
    },
    {
        en: "Until we meet again!",
        ru: "До новой встречи!",
        topic: "greetings",
        altEn: ["til we meet again"],
        altRu: [],
    },
    {
        en: "Have a nice day!",
        ru: "Хорошего дня!",
        topic: "greetings",
        altEn: ["have a good day"],
        altRu: ["хорошего тебе дня", "хорошего вам дня"],
    },
    {
        en: "Have a good weekend",
        ru: "Хороших выходных",
        topic: "greetings",
        altEn: ["have a great weekend"],
        altRu: [],
    },
    {
        en: "Say hi to…",
        ru: "Передавай привет…",
        topic: "greetings",
        altEn: ["give my regards to"],
        altRu: ["передай привет", "передайте привет", "передавайте привет"],
    },
    {
        en: "In short",
        ru: "Вкратце",
        topic: "parenthesis",
        altEn: ["in brief", "briefly", "in fine"],
        altRu: ["короче", "короче говоря", "словом"],
    },
    {
        en: "What's more",
        ru: "Кроме того",
        topic: "parenthesis",
        altEn: ["what is more"],
        altRu: ["более того"],
    },
    {
        en: "By the way",
        ru: "Кстати",
        topic: "parenthesis",
        altEn: ["by the by", "to the point",  "by the bye", "by this token"],
        altRu: ["кстати говоря", "между прочим"],
    },
    {
        en: "Most likely",
        ru: "Скорее всего",
        topic: "consents",
        altEn: ["probably", "likely"],
        altRu: ["вероятнее всего", "наиболее вероятно"],
    },
    {
        en: "Very well",
        ru: "Очень хорошо",
        topic: "consents",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "No doubt",
        ru: "Без сомнения",
        topic: "consents",
        altEn: ["without a doubt", "without doubt"],
        altRu: ["без сомнений", "нет сомнений", "нет сомнения", "никаких сомнений", "никакого сомнения"],
    },
    {
        en: "Thank you very much",
        ru: "Большое спасибо",
        topic: "polite",
        altEn: ["thanks a lot", "many thanks"],
        altRu: ["большое тебе спасибо", "большое вам спасибо", "большое спасибо тебе", "большое спасибо вам", "огромное спасибо", "большая благодарность, огромная благодарность"],
    },
    {
        en: "It's my pleasure!",
        ru: "Не стоит благодарности!",
        topic: "polite",
        altEn: ["not at all", "it is my pleasure", "do not mention it", "do not mention it"],
        altRu: ["не за что", "не надо благодарить"],
    },
    {
        en: "Nothing wrong",
        ru: "Ничего страшного",
        topic: "polite",
        altEn: ["thats all right", "that is all right", "no problem"],
        altRu: ["никаких проблем", "ничего такого", "все нормально", "все хорошо", "все в порядке", "всё нормально", "всё хорошо", "всё в порядке"],
    },
    {
        en: "Don’t take it to heart",
        ru: "Не принимайте близко к сердцу",
        topic: "talk",
        altEn: ["do not take it to heart"],
        altRu: ["не принимай близко к сердцу", "не принимай это близко к сердцу", "не принимайте это близко к сердцу"],
    },
    {
        en: "Where did we leave off?",
        ru: "На чем мы остановились?",
        topic: "talk",
        altEn: ["where were we"],
        altRu: ["где мы остановились"],
    },
    {
        en: "Things happen",
        ru: "Всякое бывает",
        topic: "talk",
        altEn: ["anything happens"],
        altRu: ["всякое случается", "бывает всякое", "случается всякое"],
    },
    
    {
        en: "How far is the...?",
        ru: "Как далеко до...?",
        topic: "travel",
        altEn: ["how far is it to"],
        altRu: ["насколько далеко до", "сколько до", "какое расстояние до", "сколько идти до", "как много идти до"],
    },
    {
        en: "Take this road",
        ru: "Следуйте по этой дороге",
        topic: "travel",
        altEn: ["follow this road", "take the road", "follow the road"],
        altRu: ["идите по этой дороге", "идите этой дорогой", "держитесь этой дороги", "иди по этой дороге", "иди этой дорогой", "держись этой дороги"],
    },
    {
        en: "Go straight ahead",
        ru: "Идите прямо",
        topic: "travel",
        altEn: ["go straight"],
        altRu: ["идите прямо вперед", "иди прямо", "иди прямо вперед", "идите вперед", "иди вперед"],
    },
    
    {
        en: "Once in a blue moon",
        ru: "Очень редко",
        topic: "idioms",
        altEn: [""],
        altRu: ["крайне редко", "очень редко"],
    },
    {
        en: "Make a long story short",
        ru: "Рассказывать кратко",
        topic: "idioms",
        altEn: [""],
        altRu: ["рассказать кратко"],
    },
    {
        en: "Break a leg!",
        ru: "Удачи!",
        topic: "idioms",
        altEn: [""],
        altRu: [""],
    },

    {
        en: "Get out of hand",
        ru: "Отбиться от рук",
        topic: "idioms2",
        altEn: [""],
        altRu: ["отбиваться от рук", "выйти из под контроля", "выходить из под контроля"],
    },
    {
        en: "The ball is in your court",
        ru: "Это ваше решение",
        topic: "idioms2",
        altEn: [""],
        altRu: ["это твое решение", "это было ваше решение", "это было твое решение"],
    },
    {
        en: "A bolt from the blue",
        ru: "Как снег на голову",
        topic: "idioms2",
        altEn: ["bolt from the blue"],
        altRu: ["будто снег на голову", "словно снег на голову"],
    },
    
    {
        en: "Still waters run deep",
        ru: "В тихом омуте черти водятся",
        topic: "proverbs",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "Don't bite the hand that feeds you",
        ru: "Не пили сук, на котором сидишь",
        topic: "proverbs",
        altEn: [""],
        altRu: ["Не пилите сук, на котором сидите", "не кусай руку, которая тебя кормит", "не кусайте руку, которая вас кормит"],
    },
    {
        en: "Actions speak louder than words",
        ru: "Поступки говорят больше, чем слова",
        topic: "proverbs",
        altEn: [""],
        altRu: ["дела важнее слов"],
    },
    

]