export const phrases = [
    {
        en: "See you later!",
        ru: "Увидимся позже!",
        topic: "greetings",
        altEn: ["see you soon", "see you"],
        altRu: ["до скорого", "до встречи", "до скорой встречи", "до скорых встреч", "еще увидимся", "ещё увидимся"],
    },
    {
        en: "Good luck!",
        ru: "Удачи!",
        topic: "greetings",
        altEn: [],
        altRu: [],
    },
    {
        en: "Long time no see!",
        ru: "Давно не виделись!",
        topic: "greetings",
        altEn: ["long time no see you"],
        altRu: ["давненько не виделись"],
    },
    {
        en: "How is it going?",
        ru: "Как идут дела?",
        topic: "greetings",
        altEn: ["how are things going", "howre things going", "hows it going", ],
        altRu: ["как дела", "как делишки"],
    },
    {
        en: "How's life?",
        ru: "Как жизнь?",
        topic: "greetings",
        altEn: ["how is life", "how is your life"],
        altRu: [],
    },
    {
        en: "How are things?",
        ru: "Как оно?",
        topic: "greetings",
        altEn: ["howre things"],
        altRu: ["как дела"],
    },
    {
        en: "What are you up to?",
        ru: "Чем занимаешься?",
        topic: "greetings",
        altEn: ["what are you doing", "whatre you doing", "what do you do"],
        altRu: ["что ты задумал", "что вы задумали", "чем занимаетесь", "чем вы занимаетесь", "чем ты занимаешься", "чем собираешься заняться", "чем собираетесь заняться", "чем думаешь заняться", "чем думаете заняться"],
    },
    {
        en: "What have you been up to?",
        ru: "Что ты делал все это время?",
        topic: "greetings",
        altEn: ["what did you do all this time", "whatve you been up to"],
        altRu: ["чем ты занимался все это время", "что вы делали все это время", "чем вы занимались всё это время"],
    },
    {
        en: "See you soon!",
        ru: "До скорого!",
        topic: "greetings",
        altEn: ["see you later"],
        altRu: ["до скорой встречи", "до скорых встреч", "скоро увидимся"],
    },
    {
        en: "Till next time!",
        ru: "До следующего раза!",
        topic: "greetings",
        altEn: ["untill next time"],
        altRu: ["до скорого"],
    },
    {
        en: "Take care!",
        ru: "Береги себя!",
        topic: "greetings",
        altEn: ["take care of yourself"],
        altRu: ["берегите себя", "будьте осторожны", "будь осторожен", "берегись", "берегитесь"],
    },
    {
        en: "Let's talk later!",
        ru: "Давайте поговорим позже!",
        topic: "greetings",
        altEn: ["talk to you later", "let us talk later"],
        altRu: ["поговорим позже"],
    },
    {
        en: "Until we meet again!",
        ru: "До новой встречи!",
        topic: "greetings",
        altEn: ["til we meet again"],
        altRu: [],
    },
    {
        en: "Have a nice day!",
        ru: "Хорошего дня!",
        topic: "greetings",
        altEn: ["have a good day"],
        altRu: ["хорошего тебе дня", "хорошего вам дня"],
    },
    {
        en: "Have a good weekend",
        ru: "Хороших выходных",
        topic: "greetings",
        altEn: ["have a great weekend"],
        altRu: [],
    },
    {
        en: "Say hi to…",
        ru: "Передавай привет…",
        topic: "greetings",
        altEn: ["give my regards to"],
        altRu: ["передай привет", "передайте привет", "передавайте привет"],
    },
    {
        en: "In short",
        ru: "Вкратце",
        topic: "parenthesis",
        altEn: ["in brief"],
        altRu: [""],
    },
    {
        en: "In a word",
        ru: "В двух словах",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "As far…",
        ru: "Что касается…",
        topic: "parenthesis",
        altEn: ["as to"],
        altRu: [""],
    },
    {
        en: "The thing is…",
        ru: "Дело в том, что…",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "Not to mention…",
        ru: "Не говоря уже о…",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "First of all",
        ru: "Прежде всего",
        topic: "parenthesis",
        altEn: ["above all"],
        altRu: ["в первую очередь"],
    },
    {
        en: "What's more",
        ru: "Кроме того",
        topic: "parenthesis",
        altEn: ["what is more"],
        altRu: ["более того"],
    },
    {
        en: "By the way",
        ru: "Кстати",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "After all",
        ru: "В итоге",
        topic: "parenthesis",
        altEn: [""],
        altRu: ["всётаки", "всетаки"],
    },
    {
        en: "So that…",
        ru: "Тaк чтобы…",
        topic: "parenthesis",
        altEn: ["so as to"],
        altRu: [""],
    },
    {
        en: "Just for the record",
        ru: "Для справки",
        topic: "parenthesis",
        altEn: [""],
        altRu: ["чтобы вы знали"],
    },
    {
        en: "And so on and so forth",
        ru: "И так далее",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "If I'm not mistaken",
        ru: "Если я не ошибаюсь",
        topic: "parenthesis",
        altEn: ["if i am not mistaken"],
        altRu: ["если не ошибаюсь"],
    },
    {
        en: "On the contrary",
        ru: "Наоборот",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "Either way",
        ru: "Так или иначе",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "As a rule",
        ru: "Как правило",
        topic: "parenthesis",
        altEn: [""],
        altRu: ["обычно"],
    },
    {
        en: "As well as…",
        ru: "Так же, как и…",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "All the same",
        ru: "Без разницы",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "On one hand…",
        ru: "С одной стороны…",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "On the other hand…",
        ru: "С другой стороны…",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "Such as…",
        ru: "Такой как…",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "Believe it or not, but…",
        ru: "Верите или нет, но…",
        topic: "parenthesis",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "If I recall correctly",
        ru: "Если я правильно помню",
        topic: "parenthesis",
        altEn: ["if i remember rightly"],
        altRu: [""],
    },
    {
        en: "By the way",
        ru: "Кстати",
        topic: "parenthesis",
        altEn: ["by the bye", "apropos"],
        altRu: ["между прочим"],
    },
    {
        en: "In other words",
        ru: "Другими словами",
        topic: "parenthesis",
        altEn: [""],
        altRu: ["иначе говоря"],
    },
    {
        en: "As I said before",
        ru: "Как я уже говорил",
        topic: "parenthesis",
        altEn: ["as i already said", "as I have said"],
        altRu: ["как я сказал раньше", "как я говорил раньше", "как я уже сказал"],
    },
    {
        en: "Most likely",
        ru: "Скорее всего",
        topic: "consents",
        altEn: ["probably", "likely"],
        altRu: ["вероятнее всего", "наиболее вероятно"],
    },
    {
        en: "Very well",
        ru: "Очень хорошо",
        topic: "consents",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "No doubt",
        ru: "Без сомнения",
        topic: "consents",
        altEn: ["without a doubt", "without doubt"],
        altRu: ["без сомнений", "нет сомнений", "нет сомнения", "никаких сомнений", "никакого сомнения"],
    },
    {
        en: "Perhaps",
        ru: "Возможно",
        topic: "consents",
        altEn: ["может быть"],
        altRu: [""],
    },
    {
        en: "Of course",
        ru: "Конечно",
        topic: "consents",
        altEn: ["sure"],
        altRu: [""],
    },
    {
        en: "Definitely",
        ru: "Определенно",
        topic: "consents",
        altEn: [""],
        altRu: ["непременно"],
    },
    {
        en: "Absolutely",
        ru: "Безусловно",
        topic: "consents",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "Naturally",
        ru: "Естественно",
        topic: "consents",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "Probably",
        ru: "Вероятно",
        topic: "consents",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "You are right",
        ru: "Вы правы",
        topic: "consents",
        altEn: ["youre right"],
        altRu: [""],
    },
    {
        en: "It can hardly be so",
        ru: "Вряд ли это так",
        topic: "consents",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "Most unlikely",
        ru: "Наиболее маловероятно",
        topic: "consents",
        altEn: [""],
        altRu: ["вряд ли"],
    },
    {
        en: "Not a bit",
        ru: "Ничуть",
        topic: "consents",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "I suppose so",
        ru: "Полагаю, что это так",
        topic: "consents",
        altEn: ["i believe so"],
        altRu: ["я полагаю что это так", "я предпополагаю что это так", "я считаю что это так", "полагаю что так", "предполагаю что так", "я предполагаю что так", "я полагаю что так", "я считаю что так"],
    },
    {
        en: "I doubt it",
        ru: "Сомневаюсь",
        topic: "consents",
        altEn: [""],
        altRu: ["я сомневаюсь", "я сомневаюсь в этом", "я сомневаюсь насчет этого", "сомневаюсь в этом", "сомневаюсь насчет этого"],
    },
    {
        en: "No way",
        ru: "Ни в коем случае",
        topic: "consents",
        altEn: [""],
        altRu: ["ни за что"],
    },
    {
        en: "Exactly so",
        ru: "Именно так",
        topic: "consents",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "Quite so",
        ru: "Вполне верно",
        topic: "consents",
        altEn: [""],
        altRu: ["вполне так"],
    },
    {
        en: "I agree with you",
        ru: "Я с вами согласен",
        topic: "consents",
        altEn: [""],
        altRu: ["я с тобой согласен"],
    },
    {
        en: "I am afraid you are wrong",
        ru: "Боюсь, что вы не правы",
        topic: "consents",
        altEn: ["im afraid you are wrong"],
        altRu: [""],
    },
    {
        en: "I am not sure",
        ru: "Не уверен",
        topic: "consents",
        altEn: ["im not sure"],
        altRu: ["я не уверен"],
    },
    {
        en: "I don't think so",
        ru: "Я так не думаю",
        topic: "consents",
        altEn: ["i do not think so"],
        altRu: [""],
    },
    {
        en: "In a way",
        ru: "В каком-то смысле",
        topic: "consents",
        altEn: ["to a certain extent"],
        altRu: ["в некотором смысле"],
    },
    {
        en: "I'm in",
        ru: "Я за",
        topic: "consents",
        altEn: ["i am in", "im game", "i am game"],
        altRu: ["я только за"],
    },
    {
        en: "I think I'll pass",
        ru: "Лучше без меня",
        topic: "consents",
        altEn: ["i think i will pass", "i will pass", "ill pass"],
        altRu: ["думаю что я пас", "думаю я пас", "думаю без меня"],
    },
    {
        en: "Deal!",
        ru: "Идёт!",
        topic: "consents",
        altEn: [""],
        altRu: ["дело", "сделка", "идет", "по рукам"],
    },
    {
        en: "It's a great idea!",
        ru: "Отличная идея!",
        topic: "consents",
        altEn: ["it is a great idea"],
        altRu: ["великолепная идея", "великолепная мысль", "отличная идея", "отличная мысль", "это великолепная идея", "это великолепная мысль", "это отличная идея", "это отличная мысль"],
    },
    {
        en: "Not a very good idea",
        ru: "Не самая хорошая идея",
        topic: "consents",
        altEn: ["not a very good think", "not a good idea"],
        altRu: ["не очень хорошая идея", "не самая лучшая идея", "не очень хорошая мысль", "не самая хорошая мысль"],
    },
    {
        en: "I'm looking forward to it",
        ru: "Жду этого с нетерпением",
        topic: "consents",
        altEn: ["i am looking forward to it"],
        altRu: ["жду это с нетерпением", "жду с нетерпением", "я с нетерпением жду этого", "я с нетерпением жду это", "я ожидаю этого с нетерпением", "я с нетерпением ожидаю этого", "я ожидаю это с нетерпением", "я с нетерпением ожидаю это"],
    },
    {
        en: "Please",
        ru: "Пожалуйста",
        topic: "polite",
        altEn: [""],
        altRu: [""],
    },
    {
        en: "Thank you",
        ru: "Спасибо",
        topic: "polite",
        altEn: ["thanks"],
        altRu: ["спасибо тебе", "спасибо вам"],
    },
    {
        en: "Thank you very much",
        ru: "Большое спасибо",
        topic: "polite",
        altEn: ["thanks a lot", "many thanks"],
        altRu: ["большое тебе спасибо", "большое вам спасибо", "большое спасибо тебе", "большое спасибо вам", "огромное спасибо", "большая благодарность, огромная благодарность"],
    },
    {
        en: "You're welcome",
        ru: "Пожалуйста (в ответ на «спасибо»)",
        topic: "polite",
        altEn: ["you are welcome"],
        altRu: ["пожалуйста"],
    },
    {
        en: "Don't mention it",
        ru: "Не стоит благодарности",
        topic: "polite",
        altEn: ["do not mention it"],
        altRu: ["не упоминайте об этом", "не упоминай об этом", "не упоминайте это", "не упоминай это", "не упоминайте про это", "не упоминай про это", "ничего", "пожалуйста"],
    },
    {
        en: "Not at all",
        ru: "Не за что",
        topic: "polite",
        altEn: [""],
        altRu: ["не стоит благодарности"],
    },
    {
        en: "No problem",
        ru: "Нет проблем",
        topic: "polite",
        altEn: ["thats all right", "that is all right", "nothing wrong"],
        altRu: ["без проблем", "никаких проблем"],
    },
    {
        en: "Nothing wrong",
        ru: "Ничего страшного",
        topic: "polite",
        altEn: ["thats all right", "that is all right", "no problem"],
        altRu: ["никаких проблем", "ничего такого", "все нормально", "все хорошо", "все в порядке", "всё нормально", "всё хорошо", "всё в порядке"],
    },
    {
        en: "Don't worry about it",
        ru: "Не беспокойтесь об этом",
        topic: "polite",
        altEn: ["do not worry about it"],
        altRu: ["не стоит беспокоиться", "не стоит беспокойства", "не надо беспокоиться об этом", "не стоит беспокоиться об этом", "не беспокойся об этом", "не беспокойтесь за это", "не беспокойся за это", "не беспокойтесь на этот счет", "не беспокойся на это счет"],
    },
    {
        en: "I'm so sorry!",
        ru: "Мне очень жаль!",
        topic: "polite",
        altEn: ["i am so sorry"],
        altRu: ["мне так жаль", "сожалею", "я сожалею", "я так сожалею"],
    },
    {
        en: "I beg your pardon!",
        ru: "Прошу прощения!",
        topic: "polite",
        altEn: ["sorry", "excuse me", "pardon me", "im sorry", "i am sorry"],
        altRu: ["извините меня пожалуйста", "простите меня пожалуйста", "извините меня", "простите меня", "извините", "простите"],
    },
    {
        en: "Sorry, I meant well",
        ru: "Извините, я хотел как лучше",
        topic: "polite",
        altEn: ["sorry i wanted the best"],
        altRu: ["простите я хотел как лучше"],
    },
    {
        en: "It's very kind of you!",
        ru: "Это очень мило с вашей стороны!",
        topic: "polite",
        altEn: ["it is very kind of you", "so nice of you", "it is so nice of you", "its so nice of you", "nice of you", "it is nice of you", "its nice of you"],
        altRu: ["с вашей стороны это очень мило", "мило с твоей стороны", "мило с вашей стороны", "очень мило с вашей стороны", "это очень мило с твоей стороны", "очень мило с твоей стороны"],
    },
    {
        en: "I'm sorry, I can't",
        ru: "Простите, не могу.",
        topic: "polite",
        altEn: ["sorry i cant", "sorry i can not", "i am sorry i can not", "i am sorry i cant", "im sorry i can not"],
        altRu: ["простите я не могу", "прости я не могу", "извините я не могу", "извини я не могу", "простите не могу", "прости не могу", "извините не могу", "извини не могу"],
    },
    {
        en: "Thank you anyway!",
        ru: "В любом случае, спасибо!",
        topic: "polite",
        altEn: ["anyway thanks", "in any case thank you"],
        altRu: ["спасибо в любом случае", "спасибо вам в любом случае", "спасибо тебе в любом случае", "в любом случае спасибо вам", "в любом случае спасибо тебе",  "спасибо так или иначе", "спасибо вам так или иначе", "спасибо тебе так или иначе", "так или иначе спасибо вам", "так или иначе спасибо тебе"],
    },
    {
        en: "Thank you in advance!",
        ru: "Спасибо заранее!",
        topic: "polite",
        altEn: ["thanks in advance"],
        altRu: ["заранее спасибо", "заранее спасибо вам", "заранее спасибо тебе", "спасибо вам заранее", "спасибо тебе заранее"],
    },
    {
        en: "May I help you?",
        ru: "Могу ли я вам помочь?",
        topic: "polite",
        altEn: ["can i help you"],
        altRu: ["я могу вам чемнибудь помочь","я могу тебе чемнибудь помочь", "могу ли я помочь", "могу ли я тебе помочь", "могу ли я вам помочь", "могу ли я помочь тебе", "могу ли я помочь вам", "я могу помочь", "я могу помочь вам", "я могу помочь тебе", "я могу вам помочь", "я могу тебе помочь", "можно помочь", "можно ли помочь", "можно вам помочь", "можно тебе помочь", "можно ли тебе помочь", "можно ли вам помочь"],
    },
    {
        en: "This way, please!",
        ru: "Сюда, пожалуйста!",
        topic: "polite",
        altEn: ["here please"],
        altRu: [""],
    },
    {
        en: "After you!",
        ru: "После вас!",
        topic: "polite",
        altEn: [""],
        altRu: ["после тебя"],
    },






]